project/apps/main/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.views.generic import TemplateView
#from django.contrib.auth.views import login, logout
from django.contrib.auth.views import LoginView, PasswordResetView

from . import views

app_name = 'main'
urlpatterns = [
    #path('test/', views.test, name="test"),
    path('accounts/', include('django.contrib.auth.urls')),
    path('registration/', views.registration, name="registration"),
    path('add_user/', views.RegisterFormView.as_view(), name = "add_user"),
    path('test/', TemplateView.as_view(template_name="test.html")),
    path('internat/', views.internat, name="internat"),
    path('kindergarten/', views.kindergarten, name="kindergarten"),
    path('rehabilitation/', views.rehabilitation, name="rehabilitation"),
    path('sponsor/', views.sponsor, name="sponsor"),
    path('vacancies/', views.vacancies, name="vacancies"),
    path('login/', 
        LoginView.as_view(
            template_name='login.html'
        ), 
        name="login"
    ),
    path('password_reset/',
        PasswordResetView.as_view(
            template_name='password_change_form.html'
        ),
        name='password_reset'
    ),
    path('index/', views.index, name="index"),
    path('my/', views.users_page, name="users_page"),
    path('get_users', views.get_json_users, name="get_json_users")
]

theme/apps/main/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.views.generic import TemplateView
#from django.contrib.auth.views import login, logout
from django.contrib.auth.views import LoginView, PasswordResetView

from . import views

app_name = 'main'
urlpatterns = [
    #path('test/', views.test, name="test"),
    path('accounts/', include('django.contrib.auth.urls')),
    path('registration/', views.registration, name="registration"),
    path('add_user/', views.RegisterFormView.as_view(), name = "add_user"),
    path('test/', TemplateView.as_view(template_name="test.html")),
    path('internat/', views.internat, name="internat"),
    path('kindergarten/', views.kindergarten, name="kindergarten"),
    path('rehabilitation/', views.rehabilitation, name="rehabilitation"),
    path('sponsor/', views.sponsor, name="sponsor"),
    path('vacancies/', views.vacancies, name="vacancies"),
    path('login/', 
        LoginView.as_view(
            template_name='login.html'
        ), 
        name="login"
    ),
    path('password_reset/',
        PasswordResetView.as_view(
            template_name='password_change_form.html'
        ),
        name='password_reset'
    ),
    path('index/', views.index, name="index"),
    path('my/', views.users_page, name="users_page")
]

theme/urls.py
from django.contrib import admin
from django.urls import path, include, re_path


'''from .apps import main
from main import main.views'''

#include('apps.main')
#from .apps import main
#from main import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
]

theme/apps/main/models.py
from django.db import models

# Create your models here.

project/apps/main/views.py
from django.shortcuts import render
from django.http import Http404, HttpResponseForbidden, HttpResponse, HttpResponseRedirect, JsonResponse
from django.urls import reverse
from django.contrib.auth.forms import UserCreationForm
from django.views.generic.edit import FormView
from django.db import models
from django.core import serializers
from django.contrib.auth.models import User

def test(request):
    return render(request, 'test_page.html')


def registration(request):
    return render(request, 'registration.html', {'form': UserCreationForm})


def index(request):
    return render(request, 'index.html')


def internat(request):
    return render(request, 'internat.html')


def kindergarten(request):
    return render(request, 'kindergarten.html')


def rehabilitation(request):
    return render(request, 'rehabilitation.html')


def sponsor(request):
    return render(request, 'internat.html')


def vacancies(request):
    return render(request, 'vacancies.html')


class RegisterFormView(FormView):
    form_class = UserCreationForm
    success_url = 'main/'
    template_name = 'registration.html'

    def form_valid(self, form):
        form.save()
        return super(RegisterFormView, self).form_valid(form)
    
    def form_invalid(self, form):
        return super(RegisterFormView, self).form_invalid(form)


def validate_registration_form(request):
    form = UserCreationForm(request.GET)
    #return HttpResponse(form.is_valid())
    if form.is_valid:
        pass
    else:
        return super(RegisterFormView, self).form_invalid(form)


def add_user(request):
    f = UserCreationForm(request.POST)
    if f.is_valid():
        f.save()
    return HttpResponseRedirect(reverse('main:test'))


def users_page(request):
    return render(request, 'user.html')


def get_json_users(request):
    users = [user.username for user in User.objects.all()]
    #usernames = serializers.serialize(usernames)
    return HttpResponse(users)

theme/apps/main/views.py
from django.shortcuts import render
from django.http import Http404, HttpResponseForbidden, HttpResponse, HttpResponseRedirect, JsonResponse
from django.urls import reverse
from django.contrib.auth.forms import UserCreationForm
from django.views.generic.edit import FormView
from django.db import models
from django.contrib.auth.models import User

def test(request):
    return render(request, 'test_page.html')


def registration(request):
    return render(request, 'registration.html', {'form': UserCreationForm})


def index(request):
    return render(request, 'index.html')


def internat(request):
    return render(request, 'internat.html')


def kindergarten(request):
    return render(request, 'kindergarten.html')


def rehabilitation(request):
    return render(request, 'rehabilitation.html')


def sponsor(request):
    return render(request, 'internat.html')


def vacancies(request):
    return render(request, 'vacancies.html')


class RegisterFormView(FormView):
    form_class = UserCreationForm
    success_url = 'articles/'
    template_name = 'registration.html'

    def form_valid(self, form):
        form.save()
        return super(RegisterFormView, self).form_valid(form)
    
    def form_invalid(self, form):
        return super(RegisterFormView, self).form_invalid(form)


def validate_registration_form(request):
    form = UserCreationForm(request.GET)
    #return HttpResponse(form.is_valid())
    if form.is_valid:
        pass
    else:
        return super(RegisterFormView, self).form_invalid(form)


def add_user(request):
    f = UserCreationForm(request.POST)
    if f.is_valid():
        f.save()
    return HttpResponseRedirect(reverse('main:test'))


def users_page(request):
    return render(request, 'user.html')

theme/templates/base.html
<!DOCTYPE html>
<html lang="en">
    {% load static %}
    {% load bootstrap4 %}
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <script type="text/javascript" src="{% static 'jquery.js' %}"></script>
        <!-- <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script> -->
        <title>{% block title %}My site{%endblock%}</title>
        <link rel="stylesheet" type="text/css" href="{% static 'main.css' %}" />
        <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" >
        <!-- Подключаем иконки -->
        <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}" >
        <script src="{% static 'main.js' %}"></script>
    </head>

    <body>
        <!-- <a href="{% url 'main:login'%}?next={{request.path}}">Login</a> -->
        
        {% block content %}

            

        {% endblock %}

    </body>

</html>

theme/templates/login.html
{% extends 'base.html' %}

{% block title %}Log in{% endblock %}

{% block content %}

{% if form.errors %}
<p>Your username and password didn't match. Please try again.</p>
{% endif %}

{% if next %}
{% if user.is_authenticated %}
  <p>Your account doesn't have access to this page. To proceed,
  please login with an account that has access.</p>
{% else %}
  <p>Please login to see this page.</p>
{% endif %}
{% endif %}

<form method="post" action="{% url 'main:login' %}">
{% csrf_token %}
<table>

<tr>
<td>{{ form.username.label_tag }}</td>
<td>{{ form.username }}</td>
</tr>

<tr>
<td>{{ form.password.label_tag }}</td>
<td>{{ form.password }}</td>
</tr>
</table>

<input type="submit" value="login" />
<input type="hidden" name="next" value="{{ next }}" />
</form>

{# Assumes you setup the password_reset view in your URLconf #}
<p><a href="{% url 'main:password_reset' %}">Lost password?</a></p>

{% endblock %}

theme/templates/password_change_form.html
{% extends "base.html" %}
{% block content %}
<div class='row'>
    <div class='col-md-4 col-10  mx-auto'>
    <h1>Change your Password</h1>
        <form method='post' action=''>{% csrf_token %}
           {{ form.as_p }}
        <span style='margin-bottom: 12px;'></span>
        <button type="submit" class='btn btn-block btn-info'>Save</button>
        </form>
      </div>
</div>
{% endblock %}

theme/templates/registration.html
{%extends 'base.html'%}

{% block title %}registration{% endblock %}

{% block content %}

<form action="{% url 'main:add_user' %}" id="registration" method="POST">
    {% csrf_token %}
    {{form.as_p }}
    <!--<input type="text" required placeholder="username" name="username"><br>
    <textarea name="password" type="password" required="" placeholder="password" cols="21" rows="1"></textarea><hr>-->
    <a href="../"><button type="submit" class="btn btn-primary btn-lg " id="load1" data-loading-text="<i class='fa fa-circle-o-notch fa-spin'></i> Processing Order">Sign up</button></a>
</form>

<!--<script>
    $(document).ready(function(){
        $('#registration').change(function(){
            //alert('Hello world');
            $.ajax({
                type: 'get',
                async: true,
                url: 'validate_registration_form',
                data: $('#registration').val(),
                success: function(data){
                    pass
                }
            });
        });
    });
</script>-->
<!--<a href="log_in"><button>Already have an account?</button></a>-->
<!--<form method="post" >
    {% csrf_token %}
    <table>
       {{ form.as_table }}
        <tr>
           <td></td>
           <td><input type="submit" name="submit" value="Register" /></td>
       </tr>
    </table>
</form>-->

{% endblock %}

theme/templates/test.html
{% extends 'base.html' %}

{% block content %}
    <p>jkhjkkjkl</p>
{% endblock %}

theme/templates/user.html
{% extends 'base.html' %}

{% block title %}Личный кабинет{% endblock %}

{% block content %}
<!-- Подключаем Bootstrap CSS -->
<link rel="stylesheet" href="css/bootstrap.min.css" >
<!-- Подключаем иконки -->
<link rel="stylesheet" href="css/font-awesome.min.css" > 
<header>
    <div class="container" style="position: relative; left: -100px;">
     <div class="row" style="padding:30px;">                         
      <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
        <nav>
            <ul class="one">
              <li><a href="#" id="logo">LOGO</a></li>                  
              <li><a href="{% url 'main:index' %}" class="one" id="pro">Про навчально- реабілітаційний центр</a></li>
              <li><a href="{% url 'main:internat' %}" class="one" id="spe">Спеціальна школа-інтернат</a></li>
              <li><a href="{% url 'main:rehabilitation' %}" class="one" id="reb">Реабілітаційний центр</a></li>
              <li><a href="{% url 'main:kindergarten' %}" class="one" id="dos">Дошкільний навчальний заклад</a></li>
              <li><a href="{% url 'main:sponsor' %}" class="two" id="spo">Спонсорство</a></li>
              <li><a href="{% url 'main:vacancies' %}" class="two" id="vak">Вакансії</a></li>
         <li><a onclick="language()" class="dropbtn two" id="kon" style="cursor: pointer"><i class="fa fa-map-marker" style="color:blue;padding-right: 5px;"></i>Контакти</a></li>
                <div id="myDropdown" class="dropdown-content">
                      <div class="container">                          
                         <div class="row">                           
                              <div class="col-md-6"> 
                            <div class="card mb-6 shadow-sm" style="position: relative;right:45px;">
  <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2541.5771794487155!2d30.445170615730635!3d50.43034897947252!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x40d4cea5f166610f%3A0x9f6c0ad5ad278f99!2z0YPQuy4g0KPRiNC40L3RgdC60L7Qs9C-LCAxNSwg0JrQuNC10LIsIDAyMDAw!5e0!3m2!1sru!2sua!4v1603009151641!5m2!1sru!2sua" width="600" height="395" frameborder="0" style="border:0;" allowfullscreen="" aria-hidden="false" tabindex="0"></iframe>
                            </div>
                          </div>
                              <div class="col-md-3"> 
                            <div class="card mb-3 shadow-sm" style="border:none;padding: 40px 0;">
                              <div class="card-body">
                                  <h2 class="card-title montserrat" style="font-size: 18px;font-weight: 600;">вул. Ушинського 15, Київ</h2>
                                  <p class="open-sans" style="font-size: 12px;font-weight: 600;">Як доїхати</p>
                                  <p class="open-sans"  style="font-size: 12px;font-weight: 400;">Від метро Шулявська
                                          Маршрутний автобус № 239, 477, 223, 227, 463, 550 до зупинки Площа Космонавтів, потім пішки 10 хвилин.
  
                                          Від метро Деміївська
                                          Маршрутний автобус № 205, 239, 477, тролейбус № 42д до зупинки Площа Космонавтів, потім пішки 10 хвилин.</p>
                              </div>
                            </div>
                                  </div>
                                  <div class="col-md-3"> 
                            <div class="card mb-3 shadow-sm" style="border:none;padding: 40px 0;">
                              <div class="card-body">
                                  <h2 style="font-size: 18px;font-weight: 600;" class="open-sans" >044 242 0996</h2>
                                <p style="font-size: 12px;font-weight: 400;" class="open-sans" >Консультації з навчання, пн-пт 09:00 − 18:00 </p>
                                  <p style="font-size: 12px;font-weight: 700;" class="open-sans" >conact@school.kiev.ua</p>
                              </div>
                            </div>                                        
                          </div>
                        </div>
                      </div>
                </div>
         <li><a href="" class="two" id="ukr" style="display: inline">Укр<i class="fa fa-chevron-down" style="color:blue;display: inline;padding-left: 5px;"></i></a></li>
            </ul>
        </nav>
    <br>
        <nav>
            <ul class="three">
                <li><a href=""id="nah">НАША МІСІЯ</a></li>
         <li><a href=""id="pid">ПІДХІД ДО НАВЧАННЯ</a></li>
         <li><a href=""id="vuk">ВИКЛАДАЧІ</a></li>
         <li><a href=""id="reb2">РЕАБІЛІТОЛОГИ</a></li>
         <li><a href=""id="vid">ВІДГУКИ</a></li>
         <li><a href=""id="dok">ДОКУМЕНТИ ЗАКЛАДУ</a></li>
         <li><a href=""id="put">ПИТАННЯ - ВІДПОВІДІ</a></li>
         <li><a href=""id="otr">ОТРИМАТИ КОНСУЛЬТАЦІЮ</a></li>
         <li>{% if user.is_authenticated %}
          <a href="{% url 'main:logout'%}?next={{request.path}}"id="vxi">ВИХІД</a>
          {% else %}
          <a href="{% url 'main:login'%}?next={% url 'main:users_page' %}"id="vxi">ВХІД</a>
          {% endif %}
          </li>
            </ul>
        </nav>
        </div>      
      </div> 
  </div> 
  </header>
  
  <script type="text/javascript">    
    function language() {
        document.getElementById("myDropdown").classList.toggle("show");
    }
    
    window.onclick = function(event) {
      if (!event.target.matches('.dropbtn')) {
    
        var dropdowns = document.getElementsByClassName("dropdown-content");
        var i;
        for (i = 0; i < dropdowns.length; i++) {
          var openDropdown = dropdowns[i];
          if (openDropdown.classList.contains('show')) {
            openDropdown.classList.remove('show');
          }
        }
      }
    }
    </script>
        <style>
    
        .dropdown {
            position: relative;
            display: inline-block;
        }
    
        .dropdown-content {
            display: none;
            position: absolute;
            top:70px;
            left: 50px;
            background-color: #FFF;
            min-width: 1200px;
            height: 400px;
            box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
            z-index: 1;
        }
    
        .dropdown-content a {
            color: black;
            padding: 12px 16px;
            text-decoration: none;
            display: block;
        }
    
    
        .show {display:block;}
        </style>     
    <h2 align="center" style="padding-top: 8%;">Hello, {{user.username}}!</h2>
    <style type="text/css">
        header{
          position: relative;
       left: 0%;
       right: 0%;
       top: 0%;
       bottom: 0%;
      
       background: #FFFFFF;
        }
        #logo{
          position: absolute;
       left: 6.08%;
       right: 78.33%;
       top: 10%;
       bottom: 47.69%;
       background: #F1F1F1;
      
       width:213px;
       height:55px; 
       top:13px; 
       left:83px; 
        }
        ul {
       list-style: none;
       margin: 0;
       padding-left: 0;
      }
      a {
       text-decoration: none;
      }
      li {
       float:left;
       margin-right:5px;
      }
      .one{
       font-family: Open Sans;
       font-style: normal;
       font-weight: normal;
       font-size: 12px;
       line-height: 18px;
       color: #000000;
      }
      .two{
       font-family: Open Sans;
       font-style: normal;
       font-weight: normal;
       font-size: 12px;
       line-height: 18px;
       color: #979797;
      }
      .three{
       font-family: Montserrat;
       font-style: normal;
       font-weight: 600;
       font-size: 12px;
       line-height: 18px;
       color: #2F4961;
      }
      #pro{
       position: absolute;
       left: 25.55%;
       right: 64.42%;
       top: 15.38%;
       bottom: 61.54%;
      
       width:137px;
       height:30px; 
       top:20px; 
       left:349px; 
      
      }
      #spe{
       position: absolute;
       left: 37.77%;
       right: 55.34%;
       top: 15.38%;
       bottom: 61.54%;
      
       width:94px;
       height:30px; 
       top:20px; 
       left:516px;
      }
      #reb{
       position: absolute;
       left: 46.85%;
       right: 46.05%;
       top: 15.38%;
       bottom: 61.54%;
      
       width:97px;
       height:30px; 
       top:20px; 
       left:640px;
      }
      #dos{
       position: absolute;
       left: 56.15%;
       right: 35.21%;
       top: 15.38%;
       bottom: 61.54%;
      
       width:118px;
       height:30px; 
       top:20px; 
       left:767px;
      }
      #spo{
       position: absolute;
       left: 70.5%;
       right: 23.65%;
       top: 24.62%;
       bottom: 61.54%;
      
       width:80px;
       height:18px; 
       top:32px; 
       left:963px;
      }
      #vak{
       position: absolute;
       left: 78.55%;
       right: 18.01%;
       top: 24.62%;
       bottom: 61.54%;
      
       width:47px;
       height:18px; 
       top:32px; 
       left:1073px;
      }
      #kon{
       position: absolute;
       left: 84.19%;
       right: 10.69%;
       top: 24.62%;
       bottom: 61.54%;
      
       width:70px;
       height:18px; 
       top:32px; 
       left:1150px;
      }
      #ukr{
       position: absolute;
       left: 91.51%;
       right: 6.15%;
       top: 24.62%;
       bottom: 61.54%;
      
       width:32px;
       height:18px; 
       top:32px; 
       left:1250px;
      }
      #nah{
       position: absolute;
       left: 0%;
       right: 90.91%;
       top: 0%;
       bottom: 0%;
      
       width:82px;
       height:18px;
       top: 96px;
       left:83px;
      
      }
      #pid{
       position: absolute;
       left: 12.42%;
       right: 71.29%;
       top: 0%;
       bottom: 0%;
      
       width:147px;
       height:18px;
       top: 96px;
       left:194px;
      }
      #vuk{
       position: absolute;
       left: 32.04%;
       right: 59.31%;
       top: 0%;
       bottom: 0%;
      
       width:78px;
       height:18px;
       top: 96px;
       left:370px;
      }
      #reb2{
       position: absolute;
       left: 44.01%;
       right: 44.24%;
       top: 0%;
       bottom: 0%;
      
       width:106px;
       height:18px;
       top: 96px;
       left:477px;
      }
      #vid{
       position: absolute;
       left: 59.09%;
       right: 34.59%;
       top: 0%;
       bottom: 0%;
      width:57px;
       height:18px;
       top: 96px;
       left:612px;
      }
      #dok{
       position: absolute;
       left: 68.74%;
       right: 14.63%;
       top: 0%;
       bottom: 0%;
      
       width:150px;
       height:18px;
       top: 96px;
       left:697px;
      }
      #put{
       position: absolute;
       left: 88.69%;
       right: -4.77%;
       top: 0%;
       bottom: 0%;
      
       width:145px;
       height:18px;
       top: 96px;
       left:874px;
      }
      #otr{
       position: absolute;
       left: 80.53%;
       right: 6.08%;
       top: 73.85%;
       bottom: 12.31%;
      
       width:183px;
       height:18px;
       top: 96px;
       left:1050px;
      }
      #vxi{
       position: absolute;
       left: 80.53%;
       right: 6.08%;
       top: 73.85%;
       bottom: 12.31%;
      
       width:47px;
       height:18px;
       top: 96px;
       left:1245px;
      }
      </style>
{% endblock %}